Feature: named parts
ModischFabrications/CutSolver pull request #60
Opened 2024-01-19 09:41 UTC by Bouni

This PR adds the ability to pass names along with the lengths which are included in the results as well.

Here's example data:
```json
{
  "cut_width": 2,
  "max_length": 1500,
  "target_sizes": [
    {
      "length": 500,
      "quantity": 2,
      "name": "Part1"
    },
    {
      "length": 200,
      "quantity": 4,
      "name": "Part2"
    }
  ]
}
```

This will allow the Frontend to show part names along with the dimensions which makes it much easier to find parts in the cutlist.

> [!CAUTION]
> This is a breaking change and the Frontend must be updated as well. I'll submit a PR for that soon

2024-01-19 09:49 UTC, Bouni commented
I just realized that the output is not rigtht (for whatever reason, the tests seem to check for the right data 🤔)

2024-01-19 10:39 UTC, Bouni commented
False alarm 🤦🏽 I had a stock length of 13000 in my example which resulted in just one element in the resulting array.

2024-01-23 09:53 UTC, ModischFabrications commented
Thanks for contributing 👍🏻
I will wait until your PR for the frontend is done, feel free to ask if anything is unclear

2024-01-24 06:00 UTC, Bouni commented
I realized a issue yesterday. I have not refactored the FFD solver yet and if a user adds to many parts it will not work.
I'll look into it today. The frontend is already done, you can check it out here: https://cutsolver.bouni.de/

2024-01-24 11:56 UTC, Bouni commented
@ModischFabrications I refactored the FFD solver as well, all tests pass and my test setup works like a charm!

![grafik](https://github.com/ModischFabrications/CutSolver/assets/948965/4f7b77a3-d463-4008-941a-75bb8aa580a1)

2024-01-24 11:59 UTC, Bouni commented
One last question, in the comment above the ffd solver is a TODO comment about the execution time being aweful. what size of test data did you use?

2024-01-27 14:28 UTC, ModischFabrications commented
> One last question, in the comment above the ffd solver is a [TODO comment](https://github.com/ModischFabrications/CutSolver/blob/master/app/solver/solver.py#L142) about the execution time being aweful. what size of test data did you use?

Not sure, it's been a while. There is a benchmarking-test somewhere in there, but I haven't set up the tests on my end again.

2024-01-28 14:42 UTC, ModischFabrications commented
@Bouni tests failed, it seems that you include py 3.11 in your dependencies but chose a py 3.12 docker image. Can you fix it, so that the CI runs through successfully? Everything else seems fine at first glance, I will merge und update the service once both PRs are done

2024-01-28 14:50 UTC, Bouni commented
I'll do that tomorrow. I think it fails because of a python 3.9 in the ci.
For me everything runs fine in a python 3.12 container

2024-01-28 14:53 UTC, ModischFabrications requested changes
I guess this could be it, CI pipenv is rather picky with it's dependencies.

2024-01-28 14:53 UTC, ModischFabrications commented on Dockerfile
> +FROM python:3.12 as build
```suggestion
FROM python:3.11 as build
```

2024-01-28 14:53 UTC, ModischFabrications commented on Dockerfile
> +FROM python:3.12-slim
```suggestion
FROM python:3.11-slim
```

2024-01-28 14:56 UTC, Bouni commented
This is what I mean

https://github.com/ModischFabrications/CutSolver/blob/master/.github%2Fworkflows%2Fci.yml#L42

2024-01-28 15:01 UTC, ModischFabrications approved these changes

2024-01-28 15:02 UTC, ModischFabrications commented
Good call, everything works now. Blocked by https://github.com/ModischFabrications/CutSolverFrontend/pull/63

2024-01-29 06:50 UTC, Bouni commented
I guess we might shoul update the python version to 3.12 as that's the current stabel release, what do you think?

2024-01-30 12:15 UTC, ModischFabrications commented
I don't see the need, but I'm open to it. Feel free to update if you prefer.

2024-01-30 12:24 UTC, Bouni commented
You're right I think we just leave it at 3.11 and update it maybe at a later point

2024-01-30 21:08 UTC, merged

2024-01-30 23:29 UTC, ModischFabrications commented
FYI: CutSolver (Backend) was promoted to v1.0.0 and got it's releases: https://hub.docker.com/r/modischfabrications/cutsolver/tags

Thanks for your support!